jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build
      run: ./mvnw --no-transfer-progress -B clean verify --file pom.xml
    strategy:
      matrix:
        java:
        - '8'
        - '11'
        - '17'
        - '21'
    timeout-minutes: 2
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
permissions:
  contents: read
